// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUCyaKKR-YxPoMkL_UOntbBXSpi0rAzP8',
    appId: '1:351885180762:web:959d5472bc4309be123d63',
    messagingSenderId: '351885180762',
    projectId: 'chat-app-2f552',
    authDomain: 'chat-app-2f552.firebaseapp.com',
    storageBucket: 'chat-app-2f552.appspot.com',
    measurementId: 'G-BWFGLC9R5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPF5ohjoNT2Iy31Y8PkhUYU8r52wkWSVU',
    appId: '1:351885180762:android:26ed69d0ecc9cc85123d63',
    messagingSenderId: '351885180762',
    projectId: 'chat-app-2f552',
    storageBucket: 'chat-app-2f552.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHqPWFfmgPyT4zPdd1p0Z3rPmrthyCTSY',
    appId: '1:351885180762:ios:8be2b24387baf367123d63',
    messagingSenderId: '351885180762',
    projectId: 'chat-app-2f552',
    storageBucket: 'chat-app-2f552.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHqPWFfmgPyT4zPdd1p0Z3rPmrthyCTSY',
    appId: '1:351885180762:ios:7c9ff94f9dac14b0123d63',
    messagingSenderId: '351885180762',
    projectId: 'chat-app-2f552',
    storageBucket: 'chat-app-2f552.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
